## Week 2: Jupyter Notebook - Pandas Introduction/Overview
Make sure to select your Kernel before starting!

Watch the [Youtube Video](https://www.youtube.com/watch?v=DkjCaAMBGWM&t=1s) I based this notebook from!

### Import Pandas Library/Package
`import pandas as pd`

In [1]:
import pandas as pd

### Optional: Displaying your Dataframe
Don't use for big datasets

In [2]:
pd.set_option("display.max_columns", None)  # Show all columns
pd.set_option("display.max_rows", None)     # Show all rows

### How to make a dataframe
`pd.DataFrame()`

In [3]:
data = {'Name': ['Zophie', 'Alice', 'Bob', 'Charlie'], 
        'Age': [7, 5, 3, 2],
        'Color': ['Gray', 'Black', 'Brown', 'White']
        }                                                       # Called a Python Dictionary

data

{'Name': ['Zophie', 'Alice', 'Bob', 'Charlie'],
 'Age': [7, 5, 3, 2],
 'Color': ['Gray', 'Black', 'Brown', 'White']}

#### Create a data frame
Store the dataframe using the `pd.DataFrame()` function into a variable called `df`

In [4]:
df = pd.DataFrame(data)
df

      Name  Age  Color
0   Zophie    7   Gray
1    Alice    5  Black
2      Bob    3  Brown
3  Charlie    2  White

### Read In Datasets
`pd.read_csv()`
Read in the file from the data folder called `Shot_Visuals_KaylanBigun_NathanTrouve.csv`

Save as `shots`

In [5]:
shots = pd.read_csv('data/Shot_Visuals_KaylanBigun_NathanTrouve.csv')

`pd.read_json()`

`pd.read_excel(x, sheet_name)`

In [6]:
shots_excel = pd.read_excel('data/(playsight)kaylan_usc.xlsx', sheet_name='Points')

### Basic Functions for Quick Analysis
`df.head()`

Gives you the **FIRST** 5 observations/rows
- If you put a number within the parentheses you will get that number of rows

In [7]:
shots.head(10)

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
0,0-0,0-0,0-0,1.0,25020.0,NaN,NaN,1,NaN,1,Deuce,Kaylan Bigun,Near,0.0,T,-18.83692,274.599344,1.0,T,-29.841596,148.910149,NaN,37.379342,-435.169001,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,2.0,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,2nd Serve In,T,NaN
1,0-0,0-0,0-0,NaN,36320.0,NaN,NaN,1,NaN,2,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-49.714545,458.469302,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.263692,-362.551121,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
2,0-0,0-0,0-0,NaN,37349.0,NaN,NaN,1,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.837555,-473.011335,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-50.312615,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,0-0,NaN,38549.0,1.0,38549.0,1,NaN,4,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-55.284077,511.099442,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.758722,-484.903489,NaN,NaN,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Nathan Trouve,NaN,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,Long
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.00000,201.000000,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN
5,30-0,0-0,0-0,1.0,61671.0,NaN,NaN,3,NaN,1,Deuce,Kaylan Bigun,Near,1.0,T,-18.00000,212.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,1st Serve In,T,NaN
6,30-0,0-0,0-0,NaN,81681.0,NaN,NaN,3,NaN,2,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-48.000000,480.000000,Down the Line,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-29.000000,-204.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Nathan Trouve,NaN,1.0,NaN,NaN,NaN,NaN,NaN,Short
7,30-0,0-0,0-0,NaN,82877.0,NaN,NaN,3,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.000000,-431.000000,Down the Line,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.000000,276.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,1.0,NaN,NaN,NaN,NaN,NaN,Short
8,30-0,0-0,0-0,NaN,84155.0,NaN,NaN,3,NaN,4,Ad,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.000000,490.000000,Crosscourt,Backhand,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-80.000000,-303.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Nathan Trouve,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Short
9,30-0,0-0,0-0,NaN,85964.0,NaN,NaN,3,NaN,5,Ad,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-96.000000,-474.000000,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.000000,315.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Short

`df.tail()`
Gives you the **LAST** 5 observations/rows

In [8]:
shots.tail()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
467,30-15,2-5,0-1,1.0,4433919.0,NaN,NaN,117,NaN,1,Ad,Nathan Trouve,Far,1.0,Body,-60.793285,-171.818154,NaN,NaN,NaN,NaN,NaN,43.360039,398.064255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,20,NaN,Kaylan Bigun,Nathan Trouve,NaN,NaN,NaN,NaN,NaN,1st Serve In,Body,NaN
468,30-15,2-5,0-1,NaN,4434580.0,NaN,NaN,117,NaN,2,Ad,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-122.080988,-434.136800,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.583503,192.648972,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,20,NaN,Kaylan Bigun,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Short
469,30-15,2-5,0-1,NaN,4436419.0,NaN,NaN,117,NaN,3,Ad,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114.231327,439.331070,Down the Line,Backhand,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.163774,-243.998803,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,20,NaN,Kaylan Bigun,Nathan Trouve,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Short
470,30-15,2-5,0-1,NaN,4439640.0,1.0,4439640.0,117,NaN,4,Ad,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.187981,228.212440,Down the Line,Forehand,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,149.959230,-172.655184,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,20,NaN,Kaylan Bigun,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,NaN,NaN,NaN
471,40-15,2-5,0-1,1.0,4457669.0,1.0,4457669.0,118,NaN,1,Deuce,Nathan Trouve,Far,1.0,T,12.432847,-233.994483,NaN,NaN,NaN,NaN,1.0,6.873114,449.561909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,20,NaN,Kaylan Bigun,Nathan Trouve,NaN,NaN,NaN,Nathan Trouve,NaN,1st Serve In,T,NaN

`df.sample()`

Gives you a **RANDOM** observation sample

Arguments: frac, random_state

In [9]:
shots.sample(5)

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
218,40-15,4-5,0-0,1.0,2120459.0,NaN,NaN,59,NaN,1,Deuce,Nathan Trouve,Near,1.0,Wide,-120.845194,209.838129,NaN,NaN,NaN,NaN,NaN,26.146845,-431.001958,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,10,NaN,Kaylan Bigun,Nathan Trouve,NaN,NaN,NaN,NaN,NaN,1st Serve In,Wide,NaN
443,40-40,2-4,0-1,NaN,4248439.0,NaN,NaN,113,1.0,10,Ad,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-91.579429,-486.766940,Down the Line,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-62.295330,424.268553,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,19,NaN,Nathan Trouve,Nathan Trouve,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deep
154,30-30,4-2,0-0,NaN,1470839.0,1.0,1472099.0,43,NaN,11,Ad,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.648234,372.347255,Down the Line,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-7.335685,-458.226936,NaN,NaN,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,7,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Nathan Trouve,1.0,NaN,NaN,Long
3,0-0,0-0,0-0,NaN,38549.0,1.0,38549.0,1,NaN,4,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-55.284077,511.099442,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.758722,-484.903489,NaN,NaN,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Nathan Trouve,NaN,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,Long
67,15-0,2-1,0-0,NaN,679809.0,NaN,NaN,19,NaN,3,Deuce,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-113.109941,500.334186,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.875760,-362.286937,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,4,NaN,Kaylan Bigun,Nathan Trouve,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deep

`df.columns`

Gives you all the column names of your dataset

In [10]:
shots.columns

Index(['pointScore', 'gameScore', 'setScore', 'isPointStart', 'pointStartTime',
       'isPointEnd', 'pointEndTime', 'pointNumber', 'isBreakPoint',
       'shotInRally', 'side', 'serverName', 'serverFarNear', 'firstServeIn',
       'firstServeZone', 'firstServeXCoord', 'firstServeYCoord',
       'secondServeIn', 'secondServeZone', 'secondServeXCoord',
       'secondServeYCoord', 'isAce', 'shotContactX', 'shotContactY',
       'shotDirection', 'shotFhBh', 'isSlice', 'isVolley', 'isOverhead',
       'isApproach', 'isDropshot', 'isExcitingPoint', 'atNetPlayer1',
       'atNetPlayer2', 'isLob', 'shotLocationX', 'shotLocationY', 'isWinner',
       'isErrorWideR', 'isErrorWideL', 'isErrorNet', 'isErrorLong',
       'clientTeam', 'Date', 'Division', 'Event', 'lineupPosition',
       'matchDetails', 'matchVenue', 'opponentTeam', 'player1Name',
       'player2Name', 'player1Hand', 'player2Hand', 'Round', 'Surface',
       'Notes', 'isTopspin', 'isFlat', 'isKick', 'gameNumber', 'tiebreakScore',
       'returnerName', 'shotHitBy', 'InsideOut', 'InsideIn', 'isDoubleFault',
       'pointWonBy', 'lastShotError', 'serveResult', 'serveInPlacement',
       'depth'],
      dtype='object')

In [11]:
shots_excel.columns

Index(['Point', 'Game', 'Set', 'Serve State', 'Match Server',
       'Host Game Score', 'Guest Game Score', 'Point Winner', 'Detail',
       'Break Point', 'Set Point', 'Favorited', 'Start Time', 'Video Time',
       'Duration'],
      dtype='object')

`df.index`

Gives you the index values in the dataframe

In [12]:
shots.index

RangeIndex(start=0, stop=472, step=1)

Use the `list()` function to see all the numbers

In [13]:
list(shots.index)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471]

`df.info()`

In [14]:
shots.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472 entries, 0 to 471
Data columns (total 72 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pointScore         472 non-null    object
 1   gameScore          472 non-null    object
 2   setScore           472 non-null    object
 3   isPointStart       118 non-null    float64
 4   pointStartTime     471 non-null    float64
 5   isPointEnd         118 non-null    float64
 6   pointEndTime       117 non-null    float64
 7   pointNumber        472 non-null    int64
 8   isBreakPoint       81 non-null     float64
 9   shotInRally        472 non-null    int64
 10  side               472 non-null    object
 11  serverName         472 non-null    object
 12  serverFarNear      472 non-null    object
 13  firstServeIn       116 non-null    float64
 14  firstServeZone     116 non-null    object
 15  firstServeXCoord   116 non-null    float64
 16  firstServeYCoord   116 non-null    float64
 17  secondServeIn      45 non-null     float64
 18  secondServeZone    45 non-null     object
 19  secondServeXCoord  45 non-null     float64
 20  secondServeYCoord  45 non-null     float64
 21  isAce              5 non-null      float64
 22  shotContactX       465 non-null    float64
 23  shotContactY       465 non-null    float64
 24  shotDirection      354 non-null    object
 25  shotFhBh           351 non-null    object
 26  isSlice            70 non-null     float64
 27  isVolley           3 non-null      float64
 28  isOverhead         2 non-null      float64
 29  isApproach         1 non-null      float64
 30  isDropshot         1 non-null      float64
 31  isExcitingPoint    0 non-null      float64
 32  atNetPlayer1       3 non-null      float64
 33  atNetPlayer2       1 non-null      float64
 34  isLob              0 non-null      float64
 35  shotLocationX      355 non-null    float64
 36  shotLocationY      355 non-null    float64
 37  isWinner           26 non-null     float64
 38  isErrorWideR       8 non-null      float64
 39  isErrorWideL       10 non-null     float64
 40  isErrorNet         59 non-null     float64
 41  isErrorLong        31 non-null     float64
 42  clientTeam         472 non-null    object
 43  Date               472 non-null    object
 44  Division           472 non-null    object
 45  Event              472 non-null    object
 46  lineupPosition     1 non-null      float64
 47  matchDetails       0 non-null      float64
 48  matchVenue         472 non-null    object
 49  opponentTeam       472 non-null    object
 50  player1Name        472 non-null    object
 51  player2Name        472 non-null    object
 52  player1Hand        472 non-null    object
 53  player2Hand        472 non-null    object
 54  Round              0 non-null      float64
 55  Surface            472 non-null    object
 56  Notes              0 non-null      float64
 57  isTopspin          198 non-null    float64
 58  isFlat             166 non-null    float64
 59  isKick             10 non-null     float64
 60  gameNumber         472 non-null    int64
 61  tiebreakScore      0 non-null      float64
 62  returnerName       472 non-null    object
 63  shotHitBy          472 non-null    object
 64  InsideOut          52 non-null     float64
 65  InsideIn           54 non-null     float64
 66  isDoubleFault      5 non-null      float64
 67  pointWonBy         118 non-null    object
 68  lastShotError      86 non-null     float64
 69  serveResult        118 non-null    object
 70  serveInPlacement   114 non-null    object
 71  depth              274 non-null    object
dtypes: float64(42), int64(3), object(27)
memory usage: 265.6+ KB

`df.describe()`

In [15]:
shots.describe() # only numerical
# shots.head()

,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,firstServeIn,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,lineupPosition,matchDetails,Round,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,InsideOut,InsideIn,isDoubleFault,lastShotError
count,118.0,4.710000e+02,118.0,1.170000e+02,472.000000,81.0,472.000000,116.000000,116.000000,116.000000,45.000000,45.000000,45.000000,5.0,465.000000,465.000000,70.0,3.0,2.0,1.0,1.0,0.0,3.0,1.0,0.0,355.000000,355.000000,26.0,8.0,10.0,59.0,31.0,1.0,0.0,0.0,0.0,198.0,166.0,10.0,472.000000,0.0,52.0,54.0,5.0,86.0
mean,1.0,2.284684e+06,1.0,2.213681e+06,62.103814,1.0,3.508475,0.612069,1.018972,6.278533,0.622222,-0.555828,81.510268,1.0,-1.876645,4.458188,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,-2.562345,24.169400,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,10.726695,NaN,1.0,1.0,1.0,1.0
std,0.0,1.311719e+06,0.0,1.325135e+06,33.705478,0.0,2.926548,0.489393,92.930666,214.363255,0.490310,88.823415,204.013913,0.0,95.061139,467.252608,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,91.833594,323.553549,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,5.647415,NaN,0.0,0.0,0.0,0.0
min,1.0,2.502000e+04,1.0,3.854900e+04,1.000000,1.0,1.000000,0.000000,-174.907409,-357.316240,0.000000,-158.068099,-246.000000,1.0,-205.137932,-559.000000,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,-212.856419,-564.116366,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,1.000000,NaN,1.0,1.0,1.0,1.0
25%,1.0,1.211054e+06,1.0,1.057069e+06,35.000000,1.0,1.750000,0.000000,-61.205370,-187.465984,0.000000,-69.107048,-154.447643,1.0,-74.721325,-463.143203,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,-79.483648,-276.164348,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,6.000000,NaN,1.0,1.0,1.0,1.0
50%,1.0,2.285176e+06,1.0,2.169659e+06,63.500000,1.0,3.000000,1.000000,9.132191,-113.950990,1.000000,-20.160176,195.738840,1.0,2.667946,223.427882,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,-3.123704,8.803128,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,11.000000,NaN,1.0,1.0,1.0,1.0
75%,1.0,3.438290e+06,1.0,3.410780e+06,90.250000,1.0,4.000000,1.000000,50.516820,241.978628,1.000000,73.484843,245.380430,1.0,61.862844,469.234558,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,72.984052,321.674459,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,15.250000,NaN,1.0,1.0,1.0,1.0
max,1.0,4.457669e+06,1.0,4.457669e+06,118.000000,1.0,19.000000,1.000000,183.301438,426.971867,1.000000,179.708809,365.158361,1.0,250.000000,617.555862,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,227.304560,648.075066,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,20.000000,NaN,1.0,1.0,1.0,1.0

`df.shape`

In [16]:
shots.shape

(472, 72)

`len()`

In [17]:
len(shots)

472

In [18]:
sample_data = range(0, 10)
len(sample_data)
# list(sample_data)

10

In [19]:
sample_data = data['Name']
len(sample_data)
# data['Name']

4

### How to Subset your Dataframe
One Column: `df[]`

Multiple Columns: `df[[ ]]`

In [20]:
shots[['pointScore']].head()

  pointScore
0        0-0
1        0-0
2        0-0
3        0-0
4       15-0

In [21]:
shots[['pointScore', 'gameScore', 'setScore']].head()

  pointScore gameScore setScore
0        0-0       0-0      0-0
1        0-0       0-0      0-0
2        0-0       0-0      0-0
3        0-0       0-0      0-0
4       15-0       0-0      0-0

### How to Filter your dataframe

`df.loc[]` and `df.iloc[]`

`df.loc[df['column'] == 'condition']`

In [22]:
shots.loc[shots['InsideOut'] == 1].head()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
1,0-0,0-0,0-0,NaN,36320.0,NaN,NaN,1,NaN,2,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-49.714545,458.469302,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.263692,-362.551121,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
2,0-0,0-0,0-0,NaN,37349.0,NaN,NaN,1,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.837555,-473.011335,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-50.312615,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,40-0,0-0,0-0,NaN,105620.0,1.0,105620.0,4,NaN,2,Ad,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114.081819,478.803674,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-168.478341,-193.353565,NaN,1.0,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,NaN
15,0-0,1-0,0-0,NaN,158580.0,1.0,158580.0,5,NaN,3,Ad,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-25.773075,-370.143373,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158.902909,468.458503,NaN,1.0,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,2,NaN,Kaylan Bigun,Nathan Trouve,1.0,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,NaN
30,30-30,1-0,0-0,NaN,278220.0,NaN,NaN,9,NaN,8,Deuce,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-45.602811,475.215256,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.823628,-341.704112,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,2,NaN,Kaylan Bigun,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short

In [23]:
shots.head()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
0,0-0,0-0,0-0,1.0,25020.0,NaN,NaN,1,NaN,1,Deuce,Kaylan Bigun,Near,0.0,T,-18.83692,274.599344,1.0,T,-29.841596,148.910149,NaN,37.379342,-435.169001,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,2.0,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,2nd Serve In,T,NaN
1,0-0,0-0,0-0,NaN,36320.0,NaN,NaN,1,NaN,2,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-49.714545,458.469302,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.263692,-362.551121,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
2,0-0,0-0,0-0,NaN,37349.0,NaN,NaN,1,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.837555,-473.011335,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-50.312615,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,0-0,NaN,38549.0,1.0,38549.0,1,NaN,4,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-55.284077,511.099442,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.758722,-484.903489,NaN,NaN,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Nathan Trouve,NaN,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,Long
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.00000,201.000000,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

In [24]:
shots.iloc[0:5]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
0,0-0,0-0,0-0,1.0,25020.0,NaN,NaN,1,NaN,1,Deuce,Kaylan Bigun,Near,0.0,T,-18.83692,274.599344,1.0,T,-29.841596,148.910149,NaN,37.379342,-435.169001,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,2.0,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,2nd Serve In,T,NaN
1,0-0,0-0,0-0,NaN,36320.0,NaN,NaN,1,NaN,2,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-49.714545,458.469302,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.263692,-362.551121,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
2,0-0,0-0,0-0,NaN,37349.0,NaN,NaN,1,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.837555,-473.011335,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-50.312615,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,0-0,NaN,38549.0,1.0,38549.0,1,NaN,4,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-55.284077,511.099442,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.758722,-484.903489,NaN,NaN,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Nathan Trouve,NaN,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,Long
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.00000,201.000000,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

### Conditional Subsetting & Querying
`&`

`|`

In [25]:
shots['serverName'].head()

0    Kaylan Bigun
1    Kaylan Bigun
2    Kaylan Bigun
3    Kaylan Bigun
4    Kaylan Bigun
Name: serverName, dtype: object

In [26]:
# Kaylan Serving
# Ace

shots.loc[(shots['serverName'] == 'Kaylan Bigun') & (shots['isAce'] == 1)]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.0,201.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

`.query()`
1. Filter when the `serverName` is equal to `Kaylan Bigun`
2. Also Filter all of his Aces

Can use many conditions (==, != , >, <, >=, <=)

In [27]:
shots_excel = pd.read_excel('data/(playsight)kaylan_usc.xlsx', sheet_name='Shots')
shots_excel.head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
0,Kaylan Bigun,1,first_serve,Serve,Slice,86.335464,1,1,1,deep,deuce,far,-0.492128,19.061304,deep,deuce,near,0.978027,0.181941,2.421875,down the T,Out,False,22:45:24,25.020000
1,Nathan Trouve,1,none,Backhand,Flat,35.898598,1,1,1,deep,ad,near,-1.200108,5.485592,deep,deuce,far,-0.909668,24.365038,1.114258,inside in,In,False,22:45:25,26.020000
2,Kaylan Bigun,1,second_serve,Serve,Slice,81.066826,1,1,1,short,deuce,far,-0.779633,15.777584,deep,deuce,near,0.976562,0.518099,2.332031,down the T,In,False,22:45:34,35.220001
3,Nathan Trouve,2,second_return,Backhand,Flat,61.041412,1,1,1,deep,deuce,near,0.660032,2.415293,deep,deuce,far,-1.298828,23.865038,0.971680,inside out,In,False,22:45:35,36.320000
4,Kaylan Bigun,3,serve_plus_one,Forehand,Topspin,62.817978,1,1,1,out,deuce,far,-1.314453,25.694525,deep,deuce,near,0.910156,-0.470559,0.833008,inside out,Out,False,22:45:36,37.349998

In [28]:
shots.query("serverName == 'Kaylan Bigun' and isAce == 1")

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.0,201.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

In [29]:
shots_excel.columns

Index(['Player', 'Shot', 'Type', 'Stroke', 'Spin', 'Speed (MPH)', 'Point',
       'Game', 'Set', 'Bounce Depth', 'Bounce Zone', 'Bounce Side',
       'Bounce (x)', 'Bounce (y)', 'Hit Depth', 'Hit Zone', 'Hit Side',
       'Hit (x)', 'Hit (y)', 'Hit (z)', 'Direction', 'Result', 'Favorited',
       'Start Time', 'Video Time'],
      dtype='object')

In [30]:
shots_excel.query('`Speed (MPH)` > 100')

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
6,Kaylan Bigun,1,second_serve,Serve,Flat,110.786316,2,1,1,deep,ad,far,2.284124,19.640869,deep,ad,near,-2.001953,0.623191,2.349609,down the T,Out,False,22:46:43,104.949997
11,Nathan Trouve,1,first_serve,Serve,Flat,115.043945,4,1,1,deep,ad,far,2.898438,18.296926,deep,ad,near,-1.217773,0.203817,2.269531,out wide,Out,False,22:48:03,184.279999
17,Nathan Trouve,1,second_serve,Serve,Slice,120.689171,5,2,1,deep,deuce,far,-1.173526,21.427223,deep,deuce,near,0.915527,0.252415,2.164062,down the T,Out,False,22:48:40,221.880005
22,Nathan Trouve,1,first_serve,Serve,Slice,110.410797,7,2,1,short,deuce,far,-1.324739,18.212114,deep,deuce,near,1.223633,0.615378,2.371094,down the T,In,False,22:49:28,269.149994
33,Nathan Trouve,1,first_serve,Serve,Kick,103.583366,8,2,1,deep,deuce,far,-0.481523,20.106646,deep,ad,near,-1.806641,0.427878,2.490234,down the T,Out,False,22:49:58,299.350006
38,Kaylan Bigun,1,first_serve,Serve,Flat,126.093613,9,3,1,short,deuce,near,0.905529,8.206503,deep,deuce,far,-0.231567,22.740038,2.203125,down the T,In,False,22:50:38,339.079987
44,Kaylan Bigun,1,first_serve,Serve,Flat,121.144768,11,3,1,deep,deuce,near,0.520290,5.436885,deep,deuce,far,-0.210938,23.365038,1.617188,down the T,Out,False,22:51:32,393.049988
52,Kaylan Bigun,1,first_serve,Serve,Flat,108.255554,12,3,1,short,deuce,near,0.788065,7.590147,deep,ad,far,1.255859,23.542282,2.300781,down the T,Out,False,22:52:13,434.079987
104,Kaylan Bigun,1,first_serve,Serve,Flat,101.224380,24,5,1,short,ad,far,0.850903,18.208048,deep,ad,near,-1.506836,0.584128,2.279297,down the T,In,False,22:59:55,896.340027
111,Kaylan Bigun,1,first_serve,Serve,Flat,112.567017,26,5,1,short,ad,far,0.412697,18.212114,deep,ad,near,-1.662109,0.193503,2.341797,down the T,In,False,23:00:49,950.739990
117,Kaylan Bigun,1,first_serve,Serve,Flat,104.861420,27,5,1,short,ad,far,0.401453,18.273750,deep,deuce,near,0.954590,1.412253,2.310547,down the T,Out,False,23:01:17,978.010010
129,Nathan Trouve,1,first_serve,Serve,Slice,102.068214,31,6,1,short,ad,far,0.295614,18.252337,deep,ad,near,-1.935547,0.466941,2.365234,down the T,In,False,23:04:29,1170.540039
131,Nathan Trouve,1,first_serve,Serve,Kick,105.600487,32,6,1,deep,deuce,far,-3.483063,18.666100,deep,deuce,near,1.046875,0.670066,2.441406,out wide,Out,False,23:04:47,1188.369995
140,Nathan Trouve,1,second_serve,Serve,Slice,107.860924,34,6,1,deep,deuce,far,-0.679553,18.318201,deep,deuce,near,1.118164,1.060691,2.455078,down the T,Out,False,23:05:38,1239.310059
141,Nathan Trouve,1,first_serve,Serve,Kick,107.522804,35,6,1,deep,ad,far,2.775662,20.479452,deep,ad,near,-1.673828,0.459128,2.291016,out wide,Out,False,23:06:06,1267.109985
184,Nathan Trouve,1,first_serve,Serve,Flat,121.590271,44,8,1,short,deuce,near,1.833858,7.803025,deep,deuce,far,-0.138306,23.289427,2.095703,down the T,In,False,23:12:03,1624.939941
189,Nathan Trouve,1,first_serve,Serve,Flat,108.080238,45,8,1,short,ad,near,-1.188449,6.548457,deep,ad,far,1.015625,23.771288,2.332031,down the T,In,False,23:12:27,1648.300049
201,Kaylan Bigun,1,first_serve,Serve,Slice,104.336891,49,9,1,short,ad,far,3.348177,18.225574,deep,ad,near,-1.978516,0.660815,2.195312,out wide,In,False,23:14:12,1753.099976
204,Kaylan Bigun,1,first_serve,Serve,Kick,110.256676,50,9,1,short,deuce,far,-0.356118,18.274300,deep,deuce,near,0.978516,0.576316,2.427734,down the T,In,False,23:14:42,1783.300049
211,Kaylan Bigun,1,first_serve,Serve,Flat,110.967171,51,9,1,short,ad,far,1.309921,18.263353,deep,ad,near,-1.694336,0.631003,2.226562,down the T,In,False,23:15:28,1829.300049
238,Nathan Trouve,1,first_serve,Serve,Slice,106.472656,55,10,1,short,ad,far,0.885615,18.267567,deep,deuce,near,1.059570,1.131003,2.287109,down the T,Out,False,23:18:46,2027.900024
243,Nathan Trouve,1,first_serve,Serve,Flat,100.548752,56,10,1,deep,ad,far,1.196801,19.588367,deep,ad,near,-1.653320,0.646628,2.228516,down the T,Out,False,23:19:42,2083.399902
255,Nathan Trouve,1,first_serve,Serve,Slice,117.086929,58,10,1,deep,ad,far,4.040221,23.042145,deep,ad,near,-1.418945,-0.095559,2.439453,out wide,Out,False,23:20:41,2142.929932
265,Nathan Trouve,1,second_serve,Serve,Slice,122.938042,59,10,1,deep,deuce,far,-2.053125,18.320839,deep,deuce,near,1.021484,0.584128,2.494141,down the T,Out,False,23:21:47,2208.030029
273,Kaylan Bigun,1,first_serve,Serve,Flat,101.018517,61,11,1,short,ad,near,-1.121347,7.747947,deep,ad,far,1.778320,23.099413,2.408203,down the T,In,False,23:22:40,2261.449951
281,Kaylan Bigun,1,first_serve,Serve,Kick,129.921982,62,11,1,short,deuce,near,0.538454,6.110898,deep,deuce,far,-0.120850,23.365038,2.187500,down the T,In,False,23:23:37,2318.330078
283,Kaylan Bigun,1,first_serve,Serve,Flat,116.459045,63,11,1,short,ad,near,-3.930593,8.373328,deep,ad,far,1.526367,22.802538,2.431641,out wide,In,False,23:23:55,2336.060059
285,Kaylan Bigun,1,first_serve,Serve,Flat,117.086929,64,11,1,short,deuce,near,2.594978,7.929790,deep,deuce,far,-0.209595,23.208788,2.279297,out wide,In,False,23:24:30,2371.629883
339,Nathan Trouve,1,first_serve,Serve,Flat,103.576897,72,12,1,short,ad,near,-1.631332,7.742897,out,ad,far,1.351562,25.021288,2.343750,down the T,In,False,23:29:54,2695.590088
372,Nathan Trouve,1,first_serve,Serve,Flat,104.454910,79,14,2,short,ad,far,3.978534,17.177071,deep,ad,near,-0.554199,0.956273,1.970703,out wide,In,False,23:36:21,3082.949951
379,Nathan Trouve,1,first_serve,Serve,Slice,119.513947,82,14,2,deep,deuce,far,-1.039617,21.247305,deep,deuce,near,0.832031,0.257688,2.066406,down the T,Out,False,23:37:51,3172.719971
381,Nathan Trouve,1,second_serve,Serve,Slice,101.285225,82,14,2,short,deuce,far,-3.392186,17.784779,deep,deuce,near,0.697266,0.454843,2.160156,out wide,In,False,23:38:04,3185.250000
385,Kaylan Bigun,1,first_serve,Serve,Flat,130.596954,83,15,2,deep,deuce,near,0.487283,5.429316,deep,deuce,far,-0.148071,23.620859,1.673828,down the T,Out,False,23:38:30,3211.649902
400,Kaylan Bigun,1,first_serve,Serve,Kick,126.093613,85,15,2,short,center_line,near,0.021474,6.309115,deep,deuce,far,-0.291992,23.880663,2.285156,down the T,In,False,23:40:05,3306.820068
401,Kaylan Bigun,1,second_serve,Serve,Flat,101.416885,85,15,2,short,deuce,near,3.378550,8.166207,deep,deuce,far,-0.551270,24.146288,2.343750,out wide,In,False,23:40:19,3320.290039
407,Kaylan Bigun,1,first_serve,Serve,Flat,109.630287,86,15,2,short,deuce,near,0.128755,6.946786,deep,ad,far,1.441406,23.052538,2.351562,down the T,Out,False,23:40:58,3359.550049
410,Kaylan Bigun,1,first_serve,Serve,Flat,101.115784,87,15,2,deep,deuce,near,0.050919,4.808718,deep,deuce,far,-0.391357,24.240038,2.337891,down the T,Out,False,23:41:38,3399.250000
429,Nathan Trouve,1,first_serve,Serve,Flat,103.576897,91,16,2,short,deuce,near,0.915160,6.877904,deep,deuce,far,-0.771973,22.927538,2.462891,down the T,In,False,23:44:39,3580.679932
463,Kaylan Bigun,1,first_serve,Serve,Slice,105.956909,100,17,2,deep,deuce_alley,far,-4.569581,22.181734,deep,deuce,near,0.919434,1.115378,2.416016,out wide,Out,False,23:48:40,3821.909912
477,Nathan Trouve,1,first_serve,Serve,Flat,110.563896,104,18,2,short,ad,far,0.633726,18.195896,deep,ad,near,-1.747070,0.545066,2.318359,down the T,In,False,23:52:04,4025.709961
485,Kaylan Bigun,1,first_serve,Serve,Flat,106.193489,106,19,2,short,ad,near,-1.111097,7.986207,deep,ad,far,1.619141,23.380791,2.435547,down the T,In,False,23:52:51,4072.209961
496,Kaylan Bigun,1,first_serve,Serve,Flat,118.787109,107,19,2,short,deuce,near,0.255883,8.012415,deep,deuce,far,-0.351318,23.755663,2.283203,down the T,In,False,23:53:39,4120.439941
500,Kaylan Bigun,1,first_serve,Serve,Flat,126.093613,108,19,2,short,ad,near,-0.727706,5.707966,deep,ad,far,1.315430,23.192524,2.359375,down the T,In,False,23:54:13,4154.740234
507,Kaylan Bigun,1,first_serve,Serve,Flat,126.866127,111,19,2,short,deuce,near,0.627582,7.555522,deep,ad,far,0.224854,22.568163,1.506836,down the T,Out,False,23:55:36,4237.740234
539,Nathan Trouve,1,first_serve,Serve,Flat,108.220818,115,20,2,short,ad,near,-1.588268,7.398328,deep,ad,far,1.132812,22.286913,2.345703,down the T,In,False,23:58:52,4433.919922

### Summarizing the Data (Numerical)
`.mean()`

`.max()`

`.min()`

`.std()`

`.var()`

`.quantile`

In [31]:
shots_excel['Speed (MPH)'].max()

130.596954

### Can also do for multiple Columns
`df[['column', 'column', ...]].mean()`

In [32]:
shots_excel[['Speed (MPH)', 'Bounce (x)']].max()

Speed (MPH)    130.596954
Bounce (x)       5.938494
dtype: float64

### Use the Aggregate Function

`.agg()`

`df[['column', 'column', ...]].agg(['mean', 'sum', 'max'])`

In [33]:
shots_excel[['Speed (MPH)', 'Bounce (x)']].agg(['mean', 'sum', 'max'])

       Speed (MPH)  Bounce (x)
mean     60.699205   -0.034155
sum   33020.367540  -18.580325
max     130.596954    5.938494

`.sum()`

In [34]:
shots_excel['Speed (MPH)'].sum()

33020.36754

`.count()`

In [35]:
shots_excel['Speed (MPH)'].count()
shots_excel.shape

(544, 25)

### Summarizing the Data (Categorial)

`.unique()`

In [36]:
shots_excel['Stroke'].unique()

# shots_excel.loc[shots_excel['Stroke'] == 'Feed']

array(['Serve', 'Backhand', 'Forehand', 'Feed', 'Volley', 'Overhead'],
      dtype=object)

`.nunique()`

Same as len(df.unique())

In [37]:
shots_excel['Stroke'].nunique()

6

`.value_counts()`

Arguments: normalize (True, False)


Find the value counts of `firstServeZone`

Find the value counts of `firstServeZone` and `firstServeIn`

In [38]:
shots_excel['Stroke'].value_counts()

Stroke
Forehand    220
Serve       157
Backhand    147
Feed         15
Volley        3
Overhead      2
Name: count, dtype: int64

### GroupBy Methods
`df.groupby()`

In [39]:
shots.head()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
0,0-0,0-0,0-0,1.0,25020.0,NaN,NaN,1,NaN,1,Deuce,Kaylan Bigun,Near,0.0,T,-18.83692,274.599344,1.0,T,-29.841596,148.910149,NaN,37.379342,-435.169001,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,2.0,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,2nd Serve In,T,NaN
1,0-0,0-0,0-0,NaN,36320.0,NaN,NaN,1,NaN,2,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-49.714545,458.469302,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.263692,-362.551121,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
2,0-0,0-0,0-0,NaN,37349.0,NaN,NaN,1,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.837555,-473.011335,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-50.312615,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,0-0,NaN,38549.0,1.0,38549.0,1,NaN,4,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-55.284077,511.099442,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.758722,-484.903489,NaN,NaN,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Nathan Trouve,NaN,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,Long
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.00000,201.000000,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

In [40]:
shots.groupby('pointNumber')['InsideOut'].sum()

# shots[shots['pointNumber'] == 80]

pointNumber
1      2.0
2      0.0
3      0.0
4      1.0
5      1.0
6      0.0
7      0.0
8      0.0
9      1.0
10     1.0
11     0.0
12     0.0
13     0.0
14     2.0
15     0.0
16     0.0
17     0.0
18     0.0
19     0.0
20     1.0
21     0.0
22     0.0
23     1.0
24     1.0
25     0.0
26     0.0
27     0.0
28     0.0
29     0.0
30     0.0
31     0.0
32     0.0
33     0.0
34     0.0
35     0.0
36     0.0
37     0.0
38     0.0
39     0.0
40     0.0
41     2.0
42     1.0
43     1.0
44     1.0
45     0.0
46     1.0
47     0.0
48     0.0
49     0.0
50     0.0
51     1.0
52     2.0
53     2.0
54     0.0
55     0.0
56     0.0
57     0.0
58     0.0
59     0.0
60     1.0
61     0.0
62     2.0
63     0.0
64     0.0
65     0.0
66     0.0
67     1.0
68     2.0
69     1.0
70     0.0
71     0.0
72     2.0
73     5.0
74     0.0
75     0.0
76     0.0
77     0.0
78     0.0
79     0.0
80     3.0
81     0.0
82     0.0
83     0.0
84     0.0
85     2.0
86     0.0
87     0.0
88     0.0
89     0.0
90     0.0
91     1.0
92     0.0
93     0.0
94     2.0
95     1.0
96     0.0
97     0.0
98     1.0
99     0.0
100    0.0
101    0.0
102    0.0
103    0.0
104    0.0
105    0.0
106    1.0
107    1.0
108    1.0
109    0.0
110    1.0
111    0.0
112    0.0
113    0.0
114    0.0
115    2.0
116    0.0
117    0.0
118    0.0
Name: InsideOut, dtype: float64

### Handling Missing Values
`.isna()`

`.dropna()`

`.fillna()`

In [41]:
shots.isna().sum()[3]

354

### How to save/write your CSV
`.to_csv()`

In [42]:
df.to_csv('cats.csv')

### Problems to Practice Yourself!!

#### Problem 1: From the `Shot_Visuals_KaylanBigun_NathanTrouve.csv` dataset, create two tables
1. Table of the **counts** of the zones Kaylan had served into for his firstServe (including made and missed)
1. Table of the **percentage** of the zones Kaylan had served into for his firstServe ((including made adn missed))

In [50]:
shots = pd.read_csv('data/Shot_Visuals_KaylanBigun_NathanTrouve.csv')
shots.loc[(shots['serverName'] == 'Kaylan Bigun') & (shots['firstServeIn'] == 1)]['firstServeZone'].value_counts()
shots.loc[(shots['serverName'] == 'Kaylan Bigun') & (shots['firstServeIn'] == 1)]['firstServeZone'].value_counts(normalize=True)

firstServeZone
T       0.500000
Wide    0.368421
Body    0.131579
Name: proportion, dtype: float64

#### Problem 2: From the `(playsight)kaylan_usc.xlsx` dataset (Download from slack!), find the minimum, maximum, and average speed of Kaylan's stroke type

In [43]:
import pandas as pd

shots_excel = pd.read_excel('data/(playsight)kaylan_usc.xlsx', sheet_name='Shots')
shots_excel.head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
0,Kaylan Bigun,1,first_serve,Serve,Slice,86.335464,1,1,1,deep,deuce,far,-0.492128,19.061304,deep,deuce,near,0.978027,0.181941,2.421875,down the T,Out,False,22:45:24,25.020000
1,Nathan Trouve,1,none,Backhand,Flat,35.898598,1,1,1,deep,ad,near,-1.200108,5.485592,deep,deuce,far,-0.909668,24.365038,1.114258,inside in,In,False,22:45:25,26.020000
2,Kaylan Bigun,1,second_serve,Serve,Slice,81.066826,1,1,1,short,deuce,far,-0.779633,15.777584,deep,deuce,near,0.976562,0.518099,2.332031,down the T,In,False,22:45:34,35.220001
3,Nathan Trouve,2,second_return,Backhand,Flat,61.041412,1,1,1,deep,deuce,near,0.660032,2.415293,deep,deuce,far,-1.298828,23.865038,0.971680,inside out,In,False,22:45:35,36.320000
4,Kaylan Bigun,3,serve_plus_one,Forehand,Topspin,62.817978,1,1,1,out,deuce,far,-1.314453,25.694525,deep,deuce,near,0.910156,-0.470559,0.833008,inside out,Out,False,22:45:36,37.349998

In [44]:
shots_excel.loc[shots_excel['Player'] == "Kaylan Bigun"].groupby('Stroke')[['Speed (MPH)']].agg(['max', 'min', 'mean'])

         Speed (MPH)
                 max        min       mean
Stroke
Backhand   77.378082  25.032770  49.743167
Feed       21.650688  17.320551  18.490169
Forehand   88.736710  24.667412  51.628206
Serve     130.596954  40.868378  88.299908
Volley     23.382744  22.516716  22.949730