## Week 2: Jupyter Notebook - Pandas Introduction/Overview
Make sure to select your Kernel before starting!

Watch the [Youtube Video](https://www.youtube.com/watch?v=DkjCaAMBGWM&t=1s) I based this notebook from!

### Import Pandas Library/Package
`import pandas as pd`

In [7]:
import pandas as pd

### Optional: Displaying your Dataframe
Don't use for big datasets

In [4]:
pd.set_option("display.max_columns", None)  # Show all columns
pd.set_option("display.max_rows", None)     # Show all rows

### How to make a dataframe
`pd.DataFrame()`

In [6]:
data = {'Name': ['Zophie', 'Alice', 'Bob', 'Charlie'], 
        'Age': [7, 5, 3, 2],
        'Color': ['Gray', 'Black', 'Brown', 'White']
        }                                                       # Called a Python Dictionary

#### Create a data frame
Store the dataframe using the `pd.DataFrame()` function into a variable called `df`

In [42]:
df = pd.DataFrame(data)
df

      Name  Age  Color
0   Zophie    7   Gray
1    Alice    5  Black
2      Bob    3  Brown
3  Charlie    2  White

### Read In Datasets
`pd.read_csv()`
Read in the file from the data folder called `Shot_Visuals_KaylanBigun_NathanTrouve.csv`

Save as `shots`

In [43]:
shots = pd.read_csv('data/Shot_Visuals_KaylanBigun_NathanTrouve.csv')

`pd.read_json()`

`pd.read_excel(x, sheet_name)`

In [44]:
shots_excel = pd.read_excel('data/(playsight)kaylan_usc.xlsx', sheet_name = 'Points')

### Basic Functions for Quick Analysis
`df.head()`

Gives you the **FIRST** 5 observations/rows
- If you put a number within the parentheses you will get that number of rows

In [45]:
shots.head()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
0,0-0,0-0,0-0,1.0,25020.0,NaN,NaN,1,NaN,1,Deuce,Kaylan Bigun,Near,0.0,T,-18.83692,274.599344,1.0,T,-29.841596,148.910149,NaN,37.379342,-435.169001,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,2.0,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,2nd Serve In,T,NaN
1,0-0,0-0,0-0,NaN,36320.0,NaN,NaN,1,NaN,2,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-49.714545,458.469302,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.263692,-362.551121,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
2,0-0,0-0,0-0,NaN,37349.0,NaN,NaN,1,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.837555,-473.011335,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-50.312615,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,0-0,NaN,38549.0,1.0,38549.0,1,NaN,4,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-55.284077,511.099442,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.758722,-484.903489,NaN,NaN,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Nathan Trouve,NaN,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,Long
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.00000,201.000000,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

`df.tail()`
Gives you the **LAST** 5 observations/rows

In [46]:
shots.tail()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
467,30-15,2-5,0-1,1.0,4433919.0,NaN,NaN,117,NaN,1,Ad,Nathan Trouve,Far,1.0,Body,-60.793285,-171.818154,NaN,NaN,NaN,NaN,NaN,43.360039,398.064255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,20,NaN,Kaylan Bigun,Nathan Trouve,NaN,NaN,NaN,NaN,NaN,1st Serve In,Body,NaN
468,30-15,2-5,0-1,NaN,4434580.0,NaN,NaN,117,NaN,2,Ad,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-122.080988,-434.136800,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.583503,192.648972,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,20,NaN,Kaylan Bigun,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Short
469,30-15,2-5,0-1,NaN,4436419.0,NaN,NaN,117,NaN,3,Ad,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114.231327,439.331070,Down the Line,Backhand,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.163774,-243.998803,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,20,NaN,Kaylan Bigun,Nathan Trouve,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Short
470,30-15,2-5,0-1,NaN,4439640.0,1.0,4439640.0,117,NaN,4,Ad,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.187981,228.212440,Down the Line,Forehand,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,149.959230,-172.655184,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,20,NaN,Kaylan Bigun,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,NaN,NaN,NaN
471,40-15,2-5,0-1,1.0,4457669.0,1.0,4457669.0,118,NaN,1,Deuce,Nathan Trouve,Far,1.0,T,12.432847,-233.994483,NaN,NaN,NaN,NaN,1.0,6.873114,449.561909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,20,NaN,Kaylan Bigun,Nathan Trouve,NaN,NaN,NaN,Nathan Trouve,NaN,1st Serve In,T,NaN

`df.sample()`

Gives you a **RANDOM** observation sample

Arguments: frac, random_state

In [47]:
shots.sample(5)

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
12,40-0,0-0,0-0,NaN,105620.0,1.0,105620.0,4,NaN,2,Ad,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114.081819,478.803674,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-168.478341,-193.353565,NaN,1.0,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,NaN
0,0-0,0-0,0-0,1.0,25020.0,NaN,NaN,1,NaN,1,Deuce,Kaylan Bigun,Near,0.0,T,-18.836920,274.599344,1.0,T,-29.841596,148.910149,NaN,37.379342,-435.169001,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,2.0,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,2nd Serve In,T,NaN
183,15-15,4-4,0-0,NaN,1790270.0,NaN,NaN,52,NaN,6,Ad,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.770828,455.478953,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-108.319526,-190.872140,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,9,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short
418,15-0,2-4,0-1,NaN,4078350.0,NaN,NaN,108,NaN,6,Ad,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-149.143635,-457.162506,Down the Line,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-27.278374,272.218241,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,19,NaN,Nathan Trouve,Nathan Trouve,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Short
395,40-40,1-3,0-1,1.0,3821909.0,NaN,NaN,102,1.0,1,Deuce,Kaylan Bigun,Near,0.0,Wide,-174.907409,394.038375,1.0,T,-19.134520,190.477318,NaN,38.500727,-465.991853,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,17,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,2nd Serve In,T,NaN

`df.columns`

Gives you all the column names of your dataset

In [48]:
shots.columns

Index(['pointScore', 'gameScore', 'setScore', 'isPointStart', 'pointStartTime',
       'isPointEnd', 'pointEndTime', 'pointNumber', 'isBreakPoint',
       'shotInRally', 'side', 'serverName', 'serverFarNear', 'firstServeIn',
       'firstServeZone', 'firstServeXCoord', 'firstServeYCoord',
       'secondServeIn', 'secondServeZone', 'secondServeXCoord',
       'secondServeYCoord', 'isAce', 'shotContactX', 'shotContactY',
       'shotDirection', 'shotFhBh', 'isSlice', 'isVolley', 'isOverhead',
       'isApproach', 'isDropshot', 'isExcitingPoint', 'atNetPlayer1',
       'atNetPlayer2', 'isLob', 'shotLocationX', 'shotLocationY', 'isWinner',
       'isErrorWideR', 'isErrorWideL', 'isErrorNet', 'isErrorLong',
       'clientTeam', 'Date', 'Division', 'Event', 'lineupPosition',
       'matchDetails', 'matchVenue', 'opponentTeam', 'player1Name',
       'player2Name', 'player1Hand', 'player2Hand', 'Round', 'Surface',
       'Notes', 'isTopspin', 'isFlat', 'isKick', 'gameNumber', 'tiebreakScore',
       'returnerName', 'shotHitBy', 'InsideOut', 'InsideIn', 'isDoubleFault',
       'pointWonBy', 'lastShotError', 'serveResult', 'serveInPlacement',
       'depth'],
      dtype='object')

In [49]:
shots_excel.columns

Index(['Point', 'Game', 'Set', 'Serve State', 'Match Server',
       'Host Game Score', 'Guest Game Score', 'Point Winner', 'Detail',
       'Break Point', 'Set Point', 'Favorited', 'Start Time', 'Video Time',
       'Duration'],
      dtype='object')

`df.index`

Gives you the index values in the dataframe

In [50]:
shots.index

RangeIndex(start=0, stop=472, step=1)

Use the `list()` function to see all the numbers

In [51]:
list(shots.index)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471]

`df.info()`

In [52]:
shots.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472 entries, 0 to 471
Data columns (total 72 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pointScore         472 non-null    object
 1   gameScore          472 non-null    object
 2   setScore           472 non-null    object
 3   isPointStart       118 non-null    float64
 4   pointStartTime     471 non-null    float64
 5   isPointEnd         118 non-null    float64
 6   pointEndTime       117 non-null    float64
 7   pointNumber        472 non-null    int64
 8   isBreakPoint       81 non-null     float64
 9   shotInRally        472 non-null    int64
 10  side               472 non-null    object
 11  serverName         472 non-null    object
 12  serverFarNear      472 non-null    object
 13  firstServeIn       116 non-null    float64
 14  firstServeZone     116 non-null    object
 15  firstServeXCoord   116 non-null    float64
 16  firstServeYCoord   116 non-null    float64
 17  secondServeIn      45 non-null     float64
 18  secondServeZone    45 non-null     object
 19  secondServeXCoord  45 non-null     float64
 20  secondServeYCoord  45 non-null     float64
 21  isAce              5 non-null      float64
 22  shotContactX       465 non-null    float64
 23  shotContactY       465 non-null    float64
 24  shotDirection      354 non-null    object
 25  shotFhBh           351 non-null    object
 26  isSlice            70 non-null     float64
 27  isVolley           3 non-null      float64
 28  isOverhead         2 non-null      float64
 29  isApproach         1 non-null      float64
 30  isDropshot         1 non-null      float64
 31  isExcitingPoint    0 non-null      float64
 32  atNetPlayer1       3 non-null      float64
 33  atNetPlayer2       1 non-null      float64
 34  isLob              0 non-null      float64
 35  shotLocationX      355 non-null    float64
 36  shotLocationY      355 non-null    float64
 37  isWinner           26 non-null     float64
 38  isErrorWideR       8 non-null      float64
 39  isErrorWideL       10 non-null     float64
 40  isErrorNet         59 non-null     float64
 41  isErrorLong        31 non-null     float64
 42  clientTeam         472 non-null    object
 43  Date               472 non-null    object
 44  Division           472 non-null    object
 45  Event              472 non-null    object
 46  lineupPosition     1 non-null      float64
 47  matchDetails       0 non-null      float64
 48  matchVenue         472 non-null    object
 49  opponentTeam       472 non-null    object
 50  player1Name        472 non-null    object
 51  player2Name        472 non-null    object
 52  player1Hand        472 non-null    object
 53  player2Hand        472 non-null    object
 54  Round              0 non-null      float64
 55  Surface            472 non-null    object
 56  Notes              0 non-null      float64
 57  isTopspin          198 non-null    float64
 58  isFlat             166 non-null    float64
 59  isKick             10 non-null     float64
 60  gameNumber         472 non-null    int64
 61  tiebreakScore      0 non-null      float64
 62  returnerName       472 non-null    object
 63  shotHitBy          472 non-null    object
 64  InsideOut          52 non-null     float64
 65  InsideIn           54 non-null     float64
 66  isDoubleFault      5 non-null      float64
 67  pointWonBy         118 non-null    object
 68  lastShotError      86 non-null     float64
 69  serveResult        118 non-null    object
 70  serveInPlacement   114 non-null    object
 71  depth              274 non-null    object
dtypes: float64(42), int64(3), object(27)
memory usage: 265.6+ KB

`df.describe()`

In [53]:
shots.describe()
shots.head()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
0,0-0,0-0,0-0,1.0,25020.0,NaN,NaN,1,NaN,1,Deuce,Kaylan Bigun,Near,0.0,T,-18.83692,274.599344,1.0,T,-29.841596,148.910149,NaN,37.379342,-435.169001,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,2.0,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,2nd Serve In,T,NaN
1,0-0,0-0,0-0,NaN,36320.0,NaN,NaN,1,NaN,2,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-49.714545,458.469302,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.263692,-362.551121,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
2,0-0,0-0,0-0,NaN,37349.0,NaN,NaN,1,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.837555,-473.011335,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-50.312615,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,0-0,NaN,38549.0,1.0,38549.0,1,NaN,4,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-55.284077,511.099442,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.758722,-484.903489,NaN,NaN,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Nathan Trouve,NaN,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,Long
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.00000,201.000000,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

`df.shape`

In [54]:
shots.shape

(472, 72)

`len()`

In [55]:
len(shots)

472

In [56]:
sample_data = range(0, 10)
len(sample_data)
list(sample_data)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [57]:
sample_data = data['Name']
len(sample_data)
# data['Name']

4

### How to Subset your Dataframe
One Column: `df[]`

Multiple Columns: `df[[ ]]`

In [59]:
shots[['pointScore']]

    pointScore
0          0-0
1          0-0
2          0-0
3          0-0
4         15-0
5         30-0
6         30-0
7         30-0
8         30-0
9         30-0
10        30-0
11        40-0
12        40-0
13         0-0
14         0-0
15         0-0
16        0-15
17        0-15
18        0-15
19        0-15
20       15-15
21       15-15
22       30-15
23       30-30
24       30-30
25       30-30
26       30-30
27       30-30
28       30-30
29       30-30
30       30-30
31       30-30
32       30-30
33       30-30
34       30-40
35       30-40
36       30-40
37         0-0
38         0-0
39        0-15
40        0-15
41        0-15
42        0-30
43        0-30
44        0-30
45        0-30
46        0-30
47        0-30
48       15-30
49       15-30
50       15-30
51       15-30
52       15-30
53       15-30
54       15-40
55       15-40
56       30-40
57       30-40
58       40-40
59       40-40
60       40-40
61       40-40
62       40-40
63         0-0
64         0-0
65        15-0
66        15-0
67        15-0
68        15-0
69        30-0
70        30-0
71        30-0
72        30-0
73        30-0
74       30-15
75       30-30
76       30-30
77       40-30
78       40-30
79       40-30
80       40-30
81       40-40
82       40-40
83       40-40
84         0-0
85         0-0
86         0-0
87         0-0
88         0-0
89         0-0
90        15-0
91        15-0
92        30-0
93        30-0
94        30-0
95       30-15
96       30-15
97       30-15
98       30-15
99       30-15
100      30-15
101      40-15
102      40-15
103      40-30
104      40-30
105      40-30
106      40-40
107      40-40
108        0-0
109        0-0
110        0-0
111       0-15
112       0-15
113      15-15
114      15-15
115      30-15
116      30-15
117      30-15
118      30-15
119      30-15
120      30-30
121      30-40
122      30-40
123      30-40
124      30-40
125      30-40
126      30-40
127      30-40
128      30-40
129      30-40
130      30-40
131      40-40
132        0-0
133        0-0
134       15-0
135       15-0
136       30-0
137       30-0
138       30-0
139      30-15
140      30-15
141      30-15
142      30-15
143      30-15
144      30-30
145      30-30
146      30-30
147      30-30
148      30-30
149      30-30
150      30-30
151      30-30
152      30-30
153      30-30
154      30-30
155      30-40
156      30-40
157      40-40
158      40-40
159      40-40
160        0-0
161        0-0
162        0-0
163        0-0
164        0-0
165       15-0
166       15-0
167       30-0
168       30-0
169       30-0
170       30-0
171       30-0
172       40-0
173        0-0
174        0-0
175       0-15
176       0-15
177       0-15
178      15-15
179      15-15
180      15-15
181      15-15
182      15-15
183      15-15
184      15-15
185      15-30
186      15-30
187      15-30
188      15-30
189      15-30
190      15-30
191      15-30
192      15-40
193      15-40
194      15-40
195      15-40
196      15-40
197      15-40
198      15-40
199      15-40
200      15-40
201      15-40
202        0-0
203        0-0
204        0-0
205        0-0
206       0-15
207       0-15
208      15-15
209      15-15
210      15-15
211      15-15
212      30-15
213      30-15
214      30-15
215      30-15
216      30-15
217      30-15
218      40-15
219      40-15
220      40-15
221      40-30
222      40-30
223      40-30
224      40-30
225      40-30
226      40-30
227      40-30
228      40-40
229      40-40
230        0-0
231        0-0
232        0-0
233        0-0
234        0-0
235       0-15
236       0-30
237       0-30
238      15-30
239      15-30
240      30-30
241      30-30
242      30-30
243      30-30
244      40-30
245      40-30
246      40-30
247      40-30
248      40-30
249      40-30
250      40-30
251      40-40
252      40-40
253      40-40
254        0-0
255        0-0
256        0-0
257        0-0
258        0-0
259        0-0
260        0-0
261        0-0
262        0-0
263        0-0
264        0-0
265       0-15
266       0-15
267      15-15
268      15-15
269      15-15
270      15-15
271      15-15
272      15-30
273      15-30
274      15-30
275      15-30
276      15-30
277      30-30
278      30-30
279      30-30
280      30-30
281      30-30
282      30-30
283      30-30
284      30-30
285      30-30
286      30-30
287      30-30
288      30-30
289      30-30
290      30-30
291      40-30
292      40-30
293      40-30
294      40-30
295        0-0
296        0-0
297        0-0
298        0-0
299       0-15
300       0-15
301       0-15
302       0-15
303      15-15
304      15-15
305      15-15
306      15-30
307      15-30
308      15-30
309      15-40
310      15-40
311      15-40
312        0-0
313        0-0
314        0-0
315        0-0
316        0-0
317        0-0
318        0-0
319       0-15
320      15-15
321      15-15
322      30-15
323      30-15
324      40-15
325      40-15
326      40-15
327        0-0
328        0-0
329        0-0
330        0-0
331        0-0
332        0-0
333        0-0
334        0-0
335        0-0
336        0-0
337       15-0
338       15-0
339       15-0
340      15-15
341      15-15
342      15-15
343      15-15
344      15-15
345      15-15
346      30-15
347      30-15
348      40-15
349      40-15
350      40-15
351      40-15
352      40-30
353      40-30
354        0-0
355        0-0
356        0-0
357        0-0
358        0-0
359       15-0
360       15-0
361       15-0
362       15-0
363       30-0
364       30-0
365       30-0
366      30-15
367      30-15
368      30-15
369      30-15
370      40-15
371      40-15
372      40-15
373      40-15
374        0-0
375        0-0
376        0-0
377        0-0
378       15-0
379       15-0
380       30-0
381       30-0
382       30-0
383      30-15
384      30-15
385      30-15
386      30-15
387      40-15
388      40-15
389      40-15
390      40-15
391      40-15
392      40-30
393      40-30
394      40-30
395      40-40
396      40-40
397        0-0
398        0-0
399        0-0
400       0-15
401       0-15
402       0-15
403       0-15
404       0-15
405       0-30
406       0-40
407       0-40
408       0-40
409        0-0
410        0-0
411        0-0
412        0-0
413       15-0
414       15-0
415       15-0
416       15-0
417       15-0
418       15-0
419       15-0
420       15-0
421       15-0
422       15-0
423       15-0
424      15-15
425      15-15
426      15-15
427      15-15
428      30-15
429      30-15
430      30-30
431      30-30
432      30-40
433      30-40
434      40-40
435      40-40
436      40-40
437      40-40
438      40-40
439      40-40
440      40-40
441      40-40
442      40-40
443      40-40
444      40-40
445      40-40
446      40-40
447      40-40
448      40-40
449      40-40
450      40-40
451      40-40
452      40-40
453        0-0
454        0-0
455        0-0
456        0-0
457       15-0
458       15-0
459       15-0
460       15-0
461       15-0
462       30-0
463       30-0
464       30-0
465       30-0
466       30-0
467      30-15
468      30-15
469      30-15
470      30-15
471      40-15

### How to Filter your dataframe

`df.loc[]` and `df.iloc[]`

`df.loc[df['column'] == 'condition']`

In [68]:
shots[['pointScore', 'gameScore', 'setScore']].head()

  pointScore gameScore setScore
0        0-0       0-0      0-0
1        0-0       0-0      0-0
2        0-0       0-0      0-0
3        0-0       0-0      0-0
4       15-0       0-0      0-0

In [62]:
shots.columns

Index(['pointScore', 'gameScore', 'setScore', 'isPointStart', 'pointStartTime',
       'isPointEnd', 'pointEndTime', 'pointNumber', 'isBreakPoint',
       'shotInRally', 'side', 'serverName', 'serverFarNear', 'firstServeIn',
       'firstServeZone', 'firstServeXCoord', 'firstServeYCoord',
       'secondServeIn', 'secondServeZone', 'secondServeXCoord',
       'secondServeYCoord', 'isAce', 'shotContactX', 'shotContactY',
       'shotDirection', 'shotFhBh', 'isSlice', 'isVolley', 'isOverhead',
       'isApproach', 'isDropshot', 'isExcitingPoint', 'atNetPlayer1',
       'atNetPlayer2', 'isLob', 'shotLocationX', 'shotLocationY', 'isWinner',
       'isErrorWideR', 'isErrorWideL', 'isErrorNet', 'isErrorLong',
       'clientTeam', 'Date', 'Division', 'Event', 'lineupPosition',
       'matchDetails', 'matchVenue', 'opponentTeam', 'player1Name',
       'player2Name', 'player1Hand', 'player2Hand', 'Round', 'Surface',
       'Notes', 'isTopspin', 'isFlat', 'isKick', 'gameNumber', 'tiebreakScore',
       'returnerName', 'shotHitBy', 'InsideOut', 'InsideIn', 'isDoubleFault',
       'pointWonBy', 'lastShotError', 'serveResult', 'serveInPlacement',
       'depth'],
      dtype='object')

In [69]:
shots.iloc[0,4]

25020.0

### Conditional Subsetting & Querying
`&`

`|`

In [70]:
shots['serverName'].head()

0    Kaylan Bigun
1    Kaylan Bigun
2    Kaylan Bigun
3    Kaylan Bigun
4    Kaylan Bigun
Name: serverName, dtype: object

In [75]:
# Kaylan Serving 
# Ace

shots.loc[(shots['serverName'] == 'Kaylan Bigun') & (shots['isAce'] == 1)]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.0,201.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

`.query()`
1. Filter when the `serverName` is equal to `Kaylan Bigun`
2. Also Filter all of his Aces

Can use many conditions (==, != , >, <, >=, <=)

In [77]:
shots_excel = pd.read_excel('data/(playsight)kaylan_usc.xlsx', sheet_name = 'Shots')
shots_excel.head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
0,Kaylan Bigun,1,first_serve,Serve,Slice,86.335464,1,1,1,deep,deuce,far,-0.492128,19.061304,deep,deuce,near,0.978027,0.181941,2.421875,down the T,Out,False,22:45:24,25.020000
1,Nathan Trouve,1,none,Backhand,Flat,35.898598,1,1,1,deep,ad,near,-1.200108,5.485592,deep,deuce,far,-0.909668,24.365038,1.114258,inside in,In,False,22:45:25,26.020000
2,Kaylan Bigun,1,second_serve,Serve,Slice,81.066826,1,1,1,short,deuce,far,-0.779633,15.777584,deep,deuce,near,0.976562,0.518099,2.332031,down the T,In,False,22:45:34,35.220001
3,Nathan Trouve,2,second_return,Backhand,Flat,61.041412,1,1,1,deep,deuce,near,0.660032,2.415293,deep,deuce,far,-1.298828,23.865038,0.971680,inside out,In,False,22:45:35,36.320000
4,Kaylan Bigun,3,serve_plus_one,Forehand,Topspin,62.817978,1,1,1,out,deuce,far,-1.314453,25.694525,deep,deuce,near,0.910156,-0.470559,0.833008,inside out,Out,False,22:45:36,37.349998

In [78]:
shots.query('serverName == "Kaylan Bigun" and isAce == 1')

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.0,201.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

In [79]:
shots_excel.columns

Index(['Player', 'Shot', 'Type', 'Stroke', 'Spin', 'Speed (MPH)', 'Point',
       'Game', 'Set', 'Bounce Depth', 'Bounce Zone', 'Bounce Side',
       'Bounce (x)', 'Bounce (y)', 'Hit Depth', 'Hit Zone', 'Hit Side',
       'Hit (x)', 'Hit (y)', 'Hit (z)', 'Direction', 'Result', 'Favorited',
       'Start Time', 'Video Time'],
      dtype='object')

In [82]:
shots_excel.query('`Speed (MPH)` > 100')

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
6,Kaylan Bigun,1,second_serve,Serve,Flat,110.786316,2,1,1,deep,ad,far,2.284124,19.640869,deep,ad,near,-2.001953,0.623191,2.349609,down the T,Out,False,22:46:43,104.949997
11,Nathan Trouve,1,first_serve,Serve,Flat,115.043945,4,1,1,deep,ad,far,2.898438,18.296926,deep,ad,near,-1.217773,0.203817,2.269531,out wide,Out,False,22:48:03,184.279999
17,Nathan Trouve,1,second_serve,Serve,Slice,120.689171,5,2,1,deep,deuce,far,-1.173526,21.427223,deep,deuce,near,0.915527,0.252415,2.164062,down the T,Out,False,22:48:40,221.880005
22,Nathan Trouve,1,first_serve,Serve,Slice,110.410797,7,2,1,short,deuce,far,-1.324739,18.212114,deep,deuce,near,1.223633,0.615378,2.371094,down the T,In,False,22:49:28,269.149994
33,Nathan Trouve,1,first_serve,Serve,Kick,103.583366,8,2,1,deep,deuce,far,-0.481523,20.106646,deep,ad,near,-1.806641,0.427878,2.490234,down the T,Out,False,22:49:58,299.350006
38,Kaylan Bigun,1,first_serve,Serve,Flat,126.093613,9,3,1,short,deuce,near,0.905529,8.206503,deep,deuce,far,-0.231567,22.740038,2.203125,down the T,In,False,22:50:38,339.079987
44,Kaylan Bigun,1,first_serve,Serve,Flat,121.144768,11,3,1,deep,deuce,near,0.520290,5.436885,deep,deuce,far,-0.210938,23.365038,1.617188,down the T,Out,False,22:51:32,393.049988
52,Kaylan Bigun,1,first_serve,Serve,Flat,108.255554,12,3,1,short,deuce,near,0.788065,7.590147,deep,ad,far,1.255859,23.542282,2.300781,down the T,Out,False,22:52:13,434.079987
104,Kaylan Bigun,1,first_serve,Serve,Flat,101.224380,24,5,1,short,ad,far,0.850903,18.208048,deep,ad,near,-1.506836,0.584128,2.279297,down the T,In,False,22:59:55,896.340027
111,Kaylan Bigun,1,first_serve,Serve,Flat,112.567017,26,5,1,short,ad,far,0.412697,18.212114,deep,ad,near,-1.662109,0.193503,2.341797,down the T,In,False,23:00:49,950.739990
117,Kaylan Bigun,1,first_serve,Serve,Flat,104.861420,27,5,1,short,ad,far,0.401453,18.273750,deep,deuce,near,0.954590,1.412253,2.310547,down the T,Out,False,23:01:17,978.010010
129,Nathan Trouve,1,first_serve,Serve,Slice,102.068214,31,6,1,short,ad,far,0.295614,18.252337,deep,ad,near,-1.935547,0.466941,2.365234,down the T,In,False,23:04:29,1170.540039
131,Nathan Trouve,1,first_serve,Serve,Kick,105.600487,32,6,1,deep,deuce,far,-3.483063,18.666100,deep,deuce,near,1.046875,0.670066,2.441406,out wide,Out,False,23:04:47,1188.369995
140,Nathan Trouve,1,second_serve,Serve,Slice,107.860924,34,6,1,deep,deuce,far,-0.679553,18.318201,deep,deuce,near,1.118164,1.060691,2.455078,down the T,Out,False,23:05:38,1239.310059
141,Nathan Trouve,1,first_serve,Serve,Kick,107.522804,35,6,1,deep,ad,far,2.775662,20.479452,deep,ad,near,-1.673828,0.459128,2.291016,out wide,Out,False,23:06:06,1267.109985
184,Nathan Trouve,1,first_serve,Serve,Flat,121.590271,44,8,1,short,deuce,near,1.833858,7.803025,deep,deuce,far,-0.138306,23.289427,2.095703,down the T,In,False,23:12:03,1624.939941
189,Nathan Trouve,1,first_serve,Serve,Flat,108.080238,45,8,1,short,ad,near,-1.188449,6.548457,deep,ad,far,1.015625,23.771288,2.332031,down the T,In,False,23:12:27,1648.300049
201,Kaylan Bigun,1,first_serve,Serve,Slice,104.336891,49,9,1,short,ad,far,3.348177,18.225574,deep,ad,near,-1.978516,0.660815,2.195312,out wide,In,False,23:14:12,1753.099976
204,Kaylan Bigun,1,first_serve,Serve,Kick,110.256676,50,9,1,short,deuce,far,-0.356118,18.274300,deep,deuce,near,0.978516,0.576316,2.427734,down the T,In,False,23:14:42,1783.300049
211,Kaylan Bigun,1,first_serve,Serve,Flat,110.967171,51,9,1,short,ad,far,1.309921,18.263353,deep,ad,near,-1.694336,0.631003,2.226562,down the T,In,False,23:15:28,1829.300049
238,Nathan Trouve,1,first_serve,Serve,Slice,106.472656,55,10,1,short,ad,far,0.885615,18.267567,deep,deuce,near,1.059570,1.131003,2.287109,down the T,Out,False,23:18:46,2027.900024
243,Nathan Trouve,1,first_serve,Serve,Flat,100.548752,56,10,1,deep,ad,far,1.196801,19.588367,deep,ad,near,-1.653320,0.646628,2.228516,down the T,Out,False,23:19:42,2083.399902
255,Nathan Trouve,1,first_serve,Serve,Slice,117.086929,58,10,1,deep,ad,far,4.040221,23.042145,deep,ad,near,-1.418945,-0.095559,2.439453,out wide,Out,False,23:20:41,2142.929932
265,Nathan Trouve,1,second_serve,Serve,Slice,122.938042,59,10,1,deep,deuce,far,-2.053125,18.320839,deep,deuce,near,1.021484,0.584128,2.494141,down the T,Out,False,23:21:47,2208.030029
273,Kaylan Bigun,1,first_serve,Serve,Flat,101.018517,61,11,1,short,ad,near,-1.121347,7.747947,deep,ad,far,1.778320,23.099413,2.408203,down the T,In,False,23:22:40,2261.449951
281,Kaylan Bigun,1,first_serve,Serve,Kick,129.921982,62,11,1,short,deuce,near,0.538454,6.110898,deep,deuce,far,-0.120850,23.365038,2.187500,down the T,In,False,23:23:37,2318.330078
283,Kaylan Bigun,1,first_serve,Serve,Flat,116.459045,63,11,1,short,ad,near,-3.930593,8.373328,deep,ad,far,1.526367,22.802538,2.431641,out wide,In,False,23:23:55,2336.060059
285,Kaylan Bigun,1,first_serve,Serve,Flat,117.086929,64,11,1,short,deuce,near,2.594978,7.929790,deep,deuce,far,-0.209595,23.208788,2.279297,out wide,In,False,23:24:30,2371.629883
339,Nathan Trouve,1,first_serve,Serve,Flat,103.576897,72,12,1,short,ad,near,-1.631332,7.742897,out,ad,far,1.351562,25.021288,2.343750,down the T,In,False,23:29:54,2695.590088
372,Nathan Trouve,1,first_serve,Serve,Flat,104.454910,79,14,2,short,ad,far,3.978534,17.177071,deep,ad,near,-0.554199,0.956273,1.970703,out wide,In,False,23:36:21,3082.949951
379,Nathan Trouve,1,first_serve,Serve,Slice,119.513947,82,14,2,deep,deuce,far,-1.039617,21.247305,deep,deuce,near,0.832031,0.257688,2.066406,down the T,Out,False,23:37:51,3172.719971
381,Nathan Trouve,1,second_serve,Serve,Slice,101.285225,82,14,2,short,deuce,far,-3.392186,17.784779,deep,deuce,near,0.697266,0.454843,2.160156,out wide,In,False,23:38:04,3185.250000
385,Kaylan Bigun,1,first_serve,Serve,Flat,130.596954,83,15,2,deep,deuce,near,0.487283,5.429316,deep,deuce,far,-0.148071,23.620859,1.673828,down the T,Out,False,23:38:30,3211.649902
400,Kaylan Bigun,1,first_serve,Serve,Kick,126.093613,85,15,2,short,center_line,near,0.021474,6.309115,deep,deuce,far,-0.291992,23.880663,2.285156,down the T,In,False,23:40:05,3306.820068
401,Kaylan Bigun,1,second_serve,Serve,Flat,101.416885,85,15,2,short,deuce,near,3.378550,8.166207,deep,deuce,far,-0.551270,24.146288,2.343750,out wide,In,False,23:40:19,3320.290039
407,Kaylan Bigun,1,first_serve,Serve,Flat,109.630287,86,15,2,short,deuce,near,0.128755,6.946786,deep,ad,far,1.441406,23.052538,2.351562,down the T,Out,False,23:40:58,3359.550049
410,Kaylan Bigun,1,first_serve,Serve,Flat,101.115784,87,15,2,deep,deuce,near,0.050919,4.808718,deep,deuce,far,-0.391357,24.240038,2.337891,down the T,Out,False,23:41:38,3399.250000
429,Nathan Trouve,1,first_serve,Serve,Flat,103.576897,91,16,2,short,deuce,near,0.915160,6.877904,deep,deuce,far,-0.771973,22.927538,2.462891,down the T,In,False,23:44:39,3580.679932
463,Kaylan Bigun,1,first_serve,Serve,Slice,105.956909,100,17,2,deep,deuce_alley,far,-4.569581,22.181734,deep,deuce,near,0.919434,1.115378,2.416016,out wide,Out,False,23:48:40,3821.909912
477,Nathan Trouve,1,first_serve,Serve,Flat,110.563896,104,18,2,short,ad,far,0.633726,18.195896,deep,ad,near,-1.747070,0.545066,2.318359,down the T,In,False,23:52:04,4025.709961
485,Kaylan Bigun,1,first_serve,Serve,Flat,106.193489,106,19,2,short,ad,near,-1.111097,7.986207,deep,ad,far,1.619141,23.380791,2.435547,down the T,In,False,23:52:51,4072.209961
496,Kaylan Bigun,1,first_serve,Serve,Flat,118.787109,107,19,2,short,deuce,near,0.255883,8.012415,deep,deuce,far,-0.351318,23.755663,2.283203,down the T,In,False,23:53:39,4120.439941
500,Kaylan Bigun,1,first_serve,Serve,Flat,126.093613,108,19,2,short,ad,near,-0.727706,5.707966,deep,ad,far,1.315430,23.192524,2.359375,down the T,In,False,23:54:13,4154.740234
507,Kaylan Bigun,1,first_serve,Serve,Flat,126.866127,111,19,2,short,deuce,near,0.627582,7.555522,deep,ad,far,0.224854,22.568163,1.506836,down the T,Out,False,23:55:36,4237.740234
539,Nathan Trouve,1,first_serve,Serve,Flat,108.220818,115,20,2,short,ad,near,-1.588268,7.398328,deep,ad,far,1.132812,22.286913,2.345703,down the T,In,False,23:58:52,4433.919922

### Summarizing the Data (Numerical)
`.mean()`

`.max()`

`.min()`

`.std()`

`.var()`

`.quantile`

In [84]:
shots_excel['Speed (MPH)'].max()

130.596954

### Can also do for multiple Columns
`df[['column', 'column', ...]].mean()`

In [87]:
shots_excel[['Speed (MPH)', 'Bounce (x)']].max()

Speed (MPH)    130.596954
Bounce (x)       5.938494
dtype: float64

### Use the Aggregate Function

`.agg()`

`df[['column', 'column', ...]].agg(['mean', 'sum', 'max'])`

In [88]:
shots_excel[['Speed (MPH)', 'Bounce (x)']].agg(['mean', 'sum', 'max'])

       Speed (MPH)  Bounce (x)
mean     60.699205   -0.034155
sum   33020.367540  -18.580325
max     130.596954    5.938494

`.sum()`

In [89]:
shots_excel['Speed (MPH)'].sum()

33020.36754

`.count()`

In [90]:
shots_excel['Speed (MPH)'].count()
shots_excel.shape

(544, 25)

### Summarizing the Data (Categorial)

`.unique()`

In [93]:
shots_excel['Stroke'].unique()
shots_excel.loc[shots_excel['Stroke'] == 'Feed']

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
37,Nathan Trouve,0,none,Feed,Flat,22.516716,9,3,1,short,deuce,far,-0.896973,15.453125,out,deuce,near,1.535156,-1.704934,0.428711,---,In,False,22:50:17,318.059998
43,Nathan Trouve,0,none,Feed,Flat,17.320551,11,3,1,deep,ad,far,0.916389,20.718750,short,deuce,near,1.386719,10.916835,0.732422,---,In,False,22:51:03,364.359985
59,Nathan Trouve,0,none,Feed,Flat,21.650688,13,3,1,deep,ad,far,0.480225,20.187500,out,deuce,near,0.891602,-1.548684,0.509277,---,In,False,22:52:40,461.149994
63,Nathan Trouve,0,none,Feed,Flat,24.248772,14,3,1,short,deuce,far,-0.735983,18.257799,deep,deuce,near,3.824219,-0.470559,1.007812,---,In,False,22:53:18,499.559998
196,Kaylan Bigun,0,none,Feed,Flat,18.276066,47,8,1,short,deuce,near,1.452148,11.570312,short,deuce,near,0.455078,9.893397,0.808594,---,Net,False,23:13:01,1682.050049
267,Nathan Trouve,0,none,Feed,Flat,20.884348,60,11,1,deep,deuce,near,1.389648,5.089844,deep,deuce,near,0.589355,0.107566,0.914062,---,Net,False,23:21:58,2219.850098
311,Kaylan Bigun,0,none,Feed,Flat,19.052607,68,12,1,deep,deuce,near,1.889648,2.617188,short,deuce,near,0.245850,11.037253,2.595703,---,Net,False,23:27:23,2544.540039
320,Kaylan Bigun,0,none,Feed,Flat,21.650688,70,12,1,deep,deuce,near,1.679688,3.804688,short,deuce,near,0.645508,11.732566,1.058594,---,Net,False,23:28:25,2606.139893
364,Kaylan Bigun,0,none,Feed,Flat,17.320551,78,14,2,short,ad,far,1.588867,14.046875,short,deuce,near,1.794922,7.420065,1.900391,---,In,False,23:35:12,3013.939941
384,Nathan Trouve,0,none,Feed,Flat,19.052607,83,15,2,short,deuce,far,-0.628906,14.882812,out,deuce,near,1.708008,-1.501809,0.727539,---,In,False,23:38:17,3198.739990
415,Nathan Trouve,0,none,Feed,Flat,17.320551,88,15,2,short,deuce,far,-0.128755,15.593551,deep,deuce,near,0.521484,2.732565,2.835938,---,In,False,23:41:57,3418.229980
424,Kaylan Bigun,0,none,Feed,Flat,17.320551,90,16,2,short,deuce,near,0.796387,7.933594,short,deuce,near,0.187134,9.534022,1.085938,---,Net,False,23:44:06,3547.129883
446,Nathan Trouve,0,none,Feed,Flat,19.918634,96,17,2,deep,ad,near,-3.316406,4.499177,deep,deuce,far,-2.863281,20.427538,1.190430,---,In,False,23:46:21,3682.429932
480,Nathan Trouve,0,none,Feed,Flat,21.650688,105,19,2,short,deuce,far,-1.554688,18.186972,deep,deuce,near,1.290039,0.545066,0.145508,---,In,False,23:52:15,4036.629883
538,Kaylan Bigun,0,none,Feed,Flat,17.320551,115,20,2,short,ad,far,1.995117,15.648438,deep,deuce,near,0.652832,4.689597,3.021484,---,In,False,23:58:42,4423.729980

`.nunique()`

Same as len(df.unique())

In [94]:
shots_excel['Stroke'].nunique()

6

`.value_counts()`

Arguments: normalize (True, False)


Find the value counts of `firstServeZone`

Find the value counts of `firstServeZone` and `firstServeIn`

In [96]:
shots_excel['Stroke'].value_counts()

Stroke
Forehand    220
Serve       157
Backhand    147
Feed         15
Volley        3
Overhead      2
Name: count, dtype: int64

### GroupBy Methods
`df.groupby()`

In [98]:
shots.head()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
0,0-0,0-0,0-0,1.0,25020.0,NaN,NaN,1,NaN,1,Deuce,Kaylan Bigun,Near,0.0,T,-18.83692,274.599344,1.0,T,-29.841596,148.910149,NaN,37.379342,-435.169001,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,2.0,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,2nd Serve In,T,NaN
1,0-0,0-0,0-0,NaN,36320.0,NaN,NaN,1,NaN,2,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-49.714545,458.469302,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.263692,-362.551121,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
2,0-0,0-0,0-0,NaN,37349.0,NaN,NaN,1,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.837555,-473.011335,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-50.312615,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,0-0,NaN,38549.0,1.0,38549.0,1,NaN,4,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-55.284077,511.099442,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.758722,-484.903489,NaN,NaN,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Nathan Trouve,NaN,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,Long
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.00000,201.000000,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

In [100]:
shots.groupby('pointNumber')['InsideOut'].sum()
shots[shots['pointNumber'] == 80]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
312,0-0,0-1,0-1,1.0,3056419.0,NaN,NaN,80,NaN,1,Deuce,Nathan Trouve,Near,1.0,Wide,-154.224645,244.409509,NaN,NaN,NaN,NaN,NaN,48.817460,-452.676963,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,14,NaN,Kaylan Bigun,Nathan Trouve,NaN,NaN,NaN,NaN,NaN,1st Serve In,Wide,NaN
313,0-0,0-1,0-1,NaN,3057340.0,NaN,NaN,80,NaN,2,Deuce,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-190.784257,453.086674,Down the Line,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-64.624989,-394.480468,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,14,NaN,Kaylan Bigun,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deep
314,0-0,0-1,0-1,NaN,3058719.0,NaN,NaN,80,NaN,3,Ad,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-43.023628,-495.139917,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.435357,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,14,NaN,Kaylan Bigun,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,0-0,0-1,0-1,NaN,3060040.0,NaN,NaN,80,NaN,4,Ad,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.330293,464.450000,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21.257180,-336.011062,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,14,NaN,Kaylan Bigun,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Short
316,0-0,0-1,0-1,NaN,3061449.0,NaN,NaN,80,NaN,5,Ad,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-43.920751,-502.017738,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113.668509,374.325727,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,14,NaN,Kaylan Bigun,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
317,0-0,0-1,0-1,NaN,3062520.0,NaN,NaN,80,NaN,6,Ad,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.912970,491.363140,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-34.613369,-205.702204,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,14,NaN,Kaylan Bigun,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Short
318,0-0,0-1,0-1,NaN,3063840.0,1.0,3063840.0,80,NaN,7,Ad,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-88.439572,-490.953428,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.359662,-212.779943,NaN,NaN,NaN,1.0,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,14,NaN,Kaylan Bigun,Nathan Trouve,1.0,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,NaN

### Handling Missing Values
`.isna()`

`.dropna()`

`.fillna()`

In [126]:
shots.isna().sum()[3]

/var/folders/q7/zjfk4hdx0ss5gnlksy_ljmqr0000gn/T/ipykernel_84505/3725304458.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  shots.isna().sum()[3]

354

### How to save/write your CSV
`.to_csv()`

In [105]:
df.to_csv('cats.csv')

### Problems to Practice Yourself!!

#### Problem 1: From the `Shot_Visuals_KaylanBigun_NathanTrouve.csv` dataset, create two tables
1. Table of the **counts** of the zones Kaylan had served into for his firstServe (including made adn missed)
1. Table of the **percentage** of the zones Kaylan had served into for his firstServe ((including made adn missed))

In [127]:
# Subsetting
# Conditional/Querying 
# value_counts() 

shots = pd.read_csv('data/Shot_Visuals_KaylanBigun_NathanTrouve.csv')
shots.loc[(shots['serverName'] == 'Kaylan Bigun') & (shots['firstServeIn'] == 1)]['firstServeZone'].value_counts()
shots.loc[(shots['serverName'] == 'Kaylan Bigun') & (shots['firstServeIn'] == 1)]['firstServeZone'].value_counts(normalize=True)

firstServeZone
T       0.500000
Wide    0.368421
Body    0.131579
Name: proportion, dtype: float64

#### Problem 2: From the `(playsight)kaylan_usc.xlsx` dataset (Download from slack!)
Find the minimum, maximum, and average speed of Kaylan's stroke type

In [128]:
# .agg() (.max(), .mean(), .sum())
# value_counts()

shots_excel = pd.read_excel('data/(playsight)kaylan_usc.xlsx', sheet_name='Shots')
shots_excel.head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
0,Kaylan Bigun,1,first_serve,Serve,Slice,86.335464,1,1,1,deep,deuce,far,-0.492128,19.061304,deep,deuce,near,0.978027,0.181941,2.421875,down the T,Out,False,22:45:24,25.020000
1,Nathan Trouve,1,none,Backhand,Flat,35.898598,1,1,1,deep,ad,near,-1.200108,5.485592,deep,deuce,far,-0.909668,24.365038,1.114258,inside in,In,False,22:45:25,26.020000
2,Kaylan Bigun,1,second_serve,Serve,Slice,81.066826,1,1,1,short,deuce,far,-0.779633,15.777584,deep,deuce,near,0.976562,0.518099,2.332031,down the T,In,False,22:45:34,35.220001
3,Nathan Trouve,2,second_return,Backhand,Flat,61.041412,1,1,1,deep,deuce,near,0.660032,2.415293,deep,deuce,far,-1.298828,23.865038,0.971680,inside out,In,False,22:45:35,36.320000
4,Kaylan Bigun,3,serve_plus_one,Forehand,Topspin,62.817978,1,1,1,out,deuce,far,-1.314453,25.694525,deep,deuce,near,0.910156,-0.470559,0.833008,inside out,Out,False,22:45:36,37.349998

In [129]:
shots_excel.loc[shots_excel['Player'] == "Kaylan Bigun"].groupby('Stroke')[['Speed (MPH)']].agg(['max', 'min', 'mean'])

         Speed (MPH)
                 max        min       mean
Stroke
Backhand   77.378082  25.032770  49.743167
Feed       21.650688  17.320551  18.490169
Forehand   88.736710  24.667412  51.628206
Serve     130.596954  40.868378  88.299908
Volley     23.382744  22.516716  22.949730